### ISSUE TITLE
Perl problem on OpenWrt

### ISSUE THREAD

**Issue by Vollpfosten** [bgewehr/fhem#5]
I'm running FHEM on Openwrt (Perl 5.20.0) but starting the Volkszaehler module gives me the error message "Can't locate object method "export_to_level" via package "JSON" at /mnt/sda1/fhem/fhem-5.6/contrib/YAF/FHEM/YAF/libs/json/JSON.pm line 112". I have exported PERL5LIB, the same installation on my Ubuntu box (Perl 5.18.2) runs without any problems. Any help is appreciated

**Comment by bgewehr** [comment]
Have you checked why the JSON modules are found in that strange location? Yaf/... Is not fhem/lib.... So first check if your fhem pearl path contains a valid JSON module!

**Comment by Vollpfosten** [comment]
Thx, but already fixed. It was related to Perl version

Am 04.04.2015 um 14:02 schrieb Bernd Gewehr:
